
version: '0.1'
services:

  apache:
    image: 'httpd:2.4'
    restart: always
    ports:
      - '80:80'
    networks:
      - 'app-network'
    depends_on:
      - php
    #volumes:
    #  - './frontend/react/build/:/usr/local/apache2/htdocs/'
  php:
    build: './backend/'
    restart: always
    ports:
      - '8080:80'
    networks:
      - 'app-network'
    depends_on:
      - mysql
    #volumes:
    #  - './backend/laravel:/var/www/html/'
  mysql:
    image: 'mysql:5.7'
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=justAlogin'
      - 'MYSQL_USER=justAlogin'
      - 'MYSQL_PASSWORD=justAloginPassword'
      - 'MYSQL_ROOT_USER=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    networks:
      - 'app-network'
    #volumes:
    #  - './database/justAlogin.sql:/docker-entrypoint-initdb.d/justAlogin.sql'
      
networks:
  app-network:
    driver: bridge
